# Auto-generated from Obsidian sources for Mistral Vibe.
# Edit the source docs or regenerate if you need updates.

DEFINITIONS = [
    {"term": "Courage", "description": "An Emotion That Describes As Having A Brave Feeling Or Strong Intense Courageous Reaction And Or Behavior And Or Response From Subtle And Or A Large Emotional Response", "category": "Positive Emotions"},
    {"term": "Faith", "description": "An Emotion That Describes A Strong Feeling Of Commitment And Power Formed From Ones Own Beliefs And Or Values And Or Virtues That Strengthen And Form From A Higher Source And Or From Oneself", "category": "Positive Emotions"},
    {"term": "Gratitude", "description": "An Emotion That Describes A Feeling Of Appreciation Or Thankfulness And Full Of Positive Feelings And Moods And Behaviors", "category": "Positive Emotions"},
    {"term": "Happiness", "description": "An Emotion That Describes A Sense Of Joy And Happy Feeling", "category": "Positive Emotions"},
    {"term": "Hope", "description": "An Emotion That Describes A Strong Sense Of Desire To Succeed Through Circumstances Where Possibility Is Low Or Below Average To Happen And The Emotion Becomes Stronger While Within That Circumstance", "category": "Positive Emotions"},
    {"term": "Joy", "description": "An Emotion Describing A Sense Of Overwhelming Satisfaction Formed From Satisfied And Happy Feelings", "category": "Positive Emotions"},
    {"term": "Love", "description": "An Emotion Describing A Feeling That Can Only Be Described By The Actions And Effects Of The Way The Person Expresses Their Moods And Or Emotions And Or Feelings And The Actions And Behaviors That Form From Them Within The Development Of Emotions Moods And Behaviors When They Create The Feelings Together", "category": "Positive Emotions"},
    {"term": "Serene", "description": "An Emotion Describing A Calm Temperant Feeling Mood Emotion And Feeling Happening Simultaneously At The Same Time", "category": "Positive Emotions"},
    {"term": "Serenity", "description": "An Emotion Describing A Sense Of Calm Understanding That Happens When Serene Emotions Moods And Behaviors Collect Together And Merge With Temperance And Calm Satisfaction", "category": "Positive Emotions"},
    {"term": "Serious", "description": "An Emotion Describing A Form Of Discipline And Focused Mindset That Is Considered Specific To The Topic And Or Way That Something Is Described", "category": "Positive Emotions"},
    {"term": "Temperance", "description": "Is A Warm Feeling Formed From Gentle And Peaceful Circumstances Or Surroundings", "category": "Positive Emotions"},
    {"term": "Calm", "description": "A Mood That Described A Form Of Inner Content And Peaceful Behavior Or Action", "category": "Moods"},
    {"term": "Cheerful", "description": "A Mood That Describes A Happy And Full Of Cheer Behavior Or Circumstance", "category": "Moods"},
    {"term": "Content", "description": "A Mood That Describes Peaceful And Relaxed Reactions Behaviors Or Actions", "category": "Moods"},
    {"term": "Defensive", "description": "A Mood That Described As Showing Defensive Or Guarded Behaviors Or Actions", "category": "Moods"},
    {"term": "Energetic", "description": "A Mood That Describes As Full Of Energy And Producing Action On That Energy Or Described As Energetic To A Vast Amount And Making Actions From The Energy Itself", "category": "Moods"},
    {"term": "Excited", "description": "A Mood That Forms Behaviors Or Actions From Excitement", "category": "Moods"},
    {"term": "Grateful", "description": "Action And Or Decisions Made From Thankfulness And Or Pleasure From Something Happening", "category": "Moods"},
    {"term": "Joyful", "description": "A Mood Described As Actions Forming From A Energy Full Of Joy", "category": "Moods"},
    {"term": "Loud", "description": "A Described Mood When Actions And Decisions Are Made From Loud Sounds Or Effects", "category": "Moods"},
    {"term": "Mellow", "description": "A Described Mood That Is More Relaxed And Considered Calm And Gentle", "category": "Moods"},
    {"term": "Narrative", "description": "A Mood Described By Speaking With A Specific Form Of Made Emphasis Or Emotions And Or Moods And Or Feelings", "category": "Moods"},
    {"term": "Neutral", "description": "A Mood That Describes Action That Is Not Positive Or Negative", "category": "Moods"},
    {"term": "Peaceful", "description": "A Mood That Describes A Content And Relaxed Action Or Behavior That Is Specific To The Form Of Peaceful Behavior From That Specific Person", "category": "Moods"},
    {"term": "Quiet", "description": "A Mood That Forms From Soft Or Low Volume Actions And Or Reactions And Or Behaviors", "category": "Moods"},
    {"term": "Relaxed", "description": "A Mood That Describes A Actions Made With A Released Amount Of Tension And Calm Feeling Or Approach For Moods And Or Behaviors And Or Also Emotions And Feelings With The Mood Itself", "category": "Moods"},
    {"term": "Talkative", "description": "A Mood That Describes Actions Made From Very Energetic Reactions Or Behaviors From Speech And Or Vocal Responses", "category": "Moods"},
    {"term": "Acceptance", "description": "A Feeling That Describes The Capability To Accept Some Kind Of Circumstance And Or Action And Or Behavior", "category": "Feelings"},
    {"term": "Admiration", "description": "A Feeling That Describes A Sense Of Respect Or Honor To Some Form Of Action And Or Cause And Or Effect", "category": "Feelings"},
    {"term": "Affectionate", "description": "A Feeling That Describes The Feel Of Affection And How Intense And Or Strong It Is", "category": "Feelings"},
    {"term": "Altruistic", "description": "A Feeling That Describes The Connection Of Strong Beliefs And Truth Values Brought Together", "category": "Feelings"},
    {"term": "Amused", "description": "A Feeling That Describes A Sense Of Enjoyment Formed From Experiencing Something Or Visually Seeing Something With Either Sight Or Vision", "category": "Feelings"},
    {"term": "Beautiful", "description": "A Feeling Of Commitment Of How Something Looks And The Feeling Is Felt When Experiencing The Quality Of The Feeling Of The Quality Of Beauty", "category": "Feelings"},
    {"term": "Blessed", "description": "A Feeling Of A Strong Emotion Of Thankfulness And Gratefulness Formed From The Emotions And Moods Of Grateful And Thankful Emotions", "category": "Feelings"},
    {"term": "Brave", "description": "A Feeling That Describes Actions That Involve Risk Or Dangerous Events Or Survival With Courage And Bravery To Enter The Circumstances While Challenging Fear With Pure Feeling", "category": "Feelings"},
    {"term": "Calm", "description": "A Feeling That Describes Feelings Forming Inner Peace Within A Sense Of Calamity Or Chaos", "category": "Feelings"},
    {"term": "Cheerful", "description": "A Feeling That Describes Feelings Full Of Cheer", "category": "Feelings"},
    {"term": "Collected", "description": "A Feeling Described As Calm And Focused And Content Simultaneously", "category": "Feelings"},
    {"term": "Concerned", "description": "A Feeling That Shows A Sense Of Worry With Content Emotions Pushing Through The Border Or Worry And Feeling", "category": "Feelings"},
    {"term": "Confident", "description": "A Feeling Described As Having A Strong Feel That The Answer Is Either Known Already Or Near To Becoming Solved", "category": "Feelings"},
    {"term": "Content", "description": "A Feeling Of Calm And Relaxed Behavior", "category": "Feelings"},
    {"term": "Courageous", "description": "A Feeling Described As Full Of Courage", "category": "Feelings"},
    {"term": "Defensive", "description": "A Feeling That Can Be Described As Feelings That Are Defending Something And Or Someone For Some Form Of Reason And Or Belief", "category": "Feelings"},
    {"term": "Determined", "description": "A Feeling So Strong That Is Described Action And Feeling Together When Forming Motivated Changes Internally Or Externally To See Success Form And Or For Something To Happen", "category": "Feelings"},
    {"term": "Eager", "description": "A Feeling Of Desire For Something To Happen That Is Upcoming Or Very Close To Happening", "category": "Feelings"},
    {"term": "Emotional", "description": "A Feeling Describing Many Emotions Coming Together Within The Chakras And Or Auras And Or Electromagnetic Field", "category": "Feelings"},
    {"term": "Empathic", "description": "A Feeling Describing The Understanding Of Others Emotions More Than Knowing Ones Own Emotions Internally", "category": "Feelings"},
    {"term": "Energetic", "description": "A Feeling Described As A Felt Emotion And Or Mood And Or Feeling That Continuously Is Filled With Energy", "category": "Feelings"},
    {"term": "Faith", "description": "A Feeling Describing The Connections Between Beliefs And Emotions As Well As Moods And Feelings While Holding Strong Desires Internally", "category": "Feelings"},
    {"term": "Faithful", "description": "A Feeling Describing Commitment And Loyalty To A Specific Action And Or Cause And Or Circumstance And Or Person", "category": "Feelings"},
    {"term": "Fascinated", "description": "A Feeling Described As Full Of Enjoyment And Satisfaction To Experiences", "category": "Feelings"},
    {"term": "Focused", "description": "A Feeling Described As Feeling A Specific Emotion Towards Something Specific With Intensity", "category": "Feelings"},
    {"term": "Full_Of_Purpose", "description": "A Feeling Described As Having A Large Amount Of Meaning And Or Definitions Given A Purpose And Meaning", "category": "Feelings"},
    {"term": "Good", "description": "A Feeling Described As Feeling Satisfaction And Positive Feelings", "category": "Feelings"},
    {"term": "Graceful", "description": "A Feeling Described As Feeling Grace And Fluid Movement Swiftly And Vividly", "category": "Feelings"},
    {"term": "Grateful", "description": "A Feeling Described As Having Thankful And Satisfaction From Blessed Circumstances", "category": "Feelings"},
    {"term": "Great", "description": "A Feeling Described As Feeling Positive And Good About The Circumstances With Confident Beliefs And Intensity Of Emotions And Moods With The Feelings", "category": "Feelings"},
    {"term": "Happy", "description": "A Feeling Described As Feeling Good And Satisfied From The Circumstances And Events That Formed The Feeling Itself", "category": "Feelings"},
    {"term": "Honor", "description": "A Feeling Described As Following Through To Ones Commitments From A Higher Being Or Entity That Brings A Sense Of Satisfaction For Living For Someone Else Instead Of Oneself", "category": "Feelings"},
    {"term": "Honorable", "description": "A Feeling Described As Good To The Commitments Made And The Promises Made", "category": "Feelings"},
    {"term": "Hopeful", "description": "A Feeling Described As Having Hope That Something Can Happen By Beliefs And Willpower Only", "category": "Feelings"},
    {"term": "Impressed", "description": "A Feeling Described As Having A Satisfied Reaction From An Action Or Effect", "category": "Feelings"},
    {"term": "Independent", "description": "A Feeling Described As Having A Strong Feeling Of Independence Made From Feelings Rather Than Moods And Emotional Behaviors", "category": "Feelings"},
    {"term": "Liked", "description": "A Feeling Described As Having Acceptance Towards Someone Else's Emotions And Or Moods And Or Feelings", "category": "Feelings"},
    {"term": "Loved", "description": "A Feeling When Love Is Happening With A Form Of Safety And Comfort And The Emotion Serenity While Feeling Content With A Relaxed Mood", "category": "Feelings"},
    {"term": "Motivated", "description": "To Be Filled With Passion And Desire And Determination To Achieve Something Such As A Goal Or Task Or Series Of Tasks And Or Goals", "category": "Feelings"},
    {"term": "Neutral", "description": "To Not Be Moved By Negative Or Positive Circumstances Or Actions", "category": "Feelings"},
    {"term": "Offensive", "description": "A Feeling That Defines A Forming Action With Feelings And Emotions", "category": "Feelings"},
    {"term": "Optimistic", "description": "A Feeling That Describes Making Actions Based On Understanding That There Is Hope And Or Faith That What Is Determined To Be Achieving With Confidence Can And Should Happen By Mindset", "category": "Feelings"},
    {"term": "Positive", "description": "A Feeling That Describes The Ability To See And Or Envision The Higher Values That Can Be Reached And For It Without Becoming Affected By Negative Feelings", "category": "Feelings"},
    {"term": "Powerful", "description": "A Feeling Described By Containing A Large Power And Considered Capable And Someone That Can Manage Self Defined Actions With That Power", "category": "Feelings"},
    {"term": "Proud", "description": "A Feeling Of Becoming Happy And Forming Satisfaction Of What Has Been Able To Succeed With Or Is Succeeding To Accomplish And Or Achieve Something", "category": "Feelings"},
    {"term": "Relaxed", "description": "A Feeling Of Contentment And Feeling Of Enjoyment Combined Together", "category": "Feelings"},
    {"term": "Relief", "description": "A Sense Of Thankful Feeling As A Sense Of Grateful Feeling Combine Together", "category": "Feelings"},
    {"term": "Selfless", "description": "A Feeling Defined As Becoming Able To Focus Towards Others Other Than Of Oneself", "category": "Feelings"},
    {"term": "Sensational", "description": "A Sense Of Enjoyment And Experience That Forms From The Haptic_Feedback Responses And Sensations And Experiences Felt", "category": "Feelings"},
    {"term": "Sensitive", "description": "A Feeling Of High Sensitivity And Or Intensity", "category": "Feelings"},
    {"term": "Social", "description": "A Feeling Of Wanting To Form Communication", "category": "Feelings"},
    {"term": "Special", "description": "A Feeling Of Unique And Individual And Abstract Simultaneously", "category": "Feelings"},
    {"term": "Strong", "description": "Having A Sense Of Feeling That Forms With Determination And Willpower While Not Failing To Allow Becoming Lesser To Form And To Stay Within The Position Of Diligence And Strength", "category": "Feelings"},
    {"term": "Surprised", "description": "A Feeling Of Succeeding Expectations Of What Was Expected To Happen", "category": "Feelings"},
    {"term": "Sympathetic", "description": "A Feeling Of Understanding Someone Through Empathic Thoughts And Or Feelings And Or Sensations", "category": "Feelings"},
    {"term": "Thankful", "description": "A Feeling Describing Relief And Gratitude Together", "category": "Feelings"},
    {"term": "Thoughtful", "description": "A Feeling Describing Positive Actions Created By Thought", "category": "Feelings"},
    {"term": "Thrilled", "description": "A Feeling Describing Immense Satisfaction", "category": "Feelings"},
    {"term": "Unique", "description": "A Feeling Describing Something Unique And Special", "category": "Feelings"},
    {"term": "Adamant", "description": "Stubbornly determined and unyielding in opinion or purpose, often focused and single-minded in pursuing goals.", "category": "Human Natures"},
    {"term": "Bashful", "description": "Shy or easily embarrassed, often avoiding attention or social interaction, and hesitant to put oneself forward.", "category": "Human Natures"},
    {"term": "Bold", "description": "Confident and courageous, willing to take risks and face challenges head-on, often with a fearless attitude.", "category": "Human Natures"},
    {"term": "Brave", "description": "Displays courage and willingness to face danger or adversity without showing fear, often taking on difficult tasks with resolve.", "category": "Human Natures"},
    {"term": "Calm", "description": "Serene and composed, not easily disturbed or excited, often maintaining a level-headed and peaceful demeanor in stressful situations.", "category": "Human Natures"},
    {"term": "Careful", "description": "Cautious and attentive to detail, often taking steps to avoid mistakes or danger, and considering potential risks before acting.", "category": "Human Natures"},
    {"term": "Docile", "description": "Gentle and easily managed or led, often compliant and cooperative, with a tendency to follow instructions without resistance.", "category": "Human Natures"},
    {"term": "Gentle", "description": "Kind and soft-hearted, with a tender and considerate approach to others, often avoiding harshness or aggression.", "category": "Human Natures"},
    {"term": "Hardy", "description": "Robust and resilient, capable of withstanding tough conditions or challenges, often showing endurance and strength.", "category": "Human Natures"},
    {"term": "Hasty", "description": "Quick to act or make decisions, often without fully considering the consequences, sometimes resulting in rash or impulsive behavior.", "category": "Human Natures"},
    {"term": "Impish", "description": "Playfully mischievous, with a tendency to cause trouble or behave in a teasing manner, often with a sense of humor.", "category": "Human Natures"},
    {"term": "Jolly", "description": "Cheerful and lighthearted, with a happy and optimistic outlook, often spreading joy and laughter to those around.", "category": "Human Natures"},
    {"term": "Lax", "description": "Relaxed and easy-going, often not strict or demanding, with a tendency to be lenient or unconcerned about details.", "category": "Human Natures"},
    {"term": "Lonely", "description": "Prefers solitude or feels isolated, often experiencing a sense of being alone or disconnected from others.", "category": "Human Natures"},
    {"term": "Mild", "description": "Gentle in nature and temperament, not prone to extreme reactions or behavior, often calm and soothing in demeanor.", "category": "Human Natures"},
    {"term": "Modest", "description": "Humble and unassuming, often downplaying one's own achievements or abilities, with a preference for avoiding the spotlight.", "category": "Human Natures"},
    {"term": "Naive", "description": "Innocent and inexperienced, often showing a lack of worldly knowledge or sophistication, with a tendency to be easily trusting.", "category": "Human Natures"},
    {"term": "Naughty", "description": "Playfully disobedient or mischievous, often delighting in breaking rules or causing minor trouble for fun.", "category": "Human Natures"},
    {"term": "Quiet", "description": "Reserved and soft-spoken, often preferring to observe rather than participate in conversation, and comfortable in silence.", "category": "Human Natures"},
    {"term": "Quirky", "description": "Unconventional and eccentric, often displaying unique or odd behavior that sets one apart from others in an endearing way.", "category": "Human Natures"},
    {"term": "Rash", "description": "Prone to acting without thinking, often making hasty decisions or taking impulsive actions that can lead to unintended consequences.", "category": "Human Natures"},
    {"term": "Relaxed", "description": "Easy-going and calm, not easily stressed or worried, often taking things in stride and maintaining a laid-back attitude.", "category": "Human Natures"},
    {"term": "Sassy", "description": "Bold and lively, often with a sharp or cheeky attitude, unafraid to speak one's mind or challenge others with wit and humor.", "category": "Human Natures"},
    {"term": "Serious", "description": "Focused and thoughtful, often taking matters with gravity and not inclined to humor or lightheartedness, with a strong sense of responsibility.", "category": "Human Natures"},
    {"term": "Timid", "description": "Shy and easily frightened, often hesitant to take risks or step outside of comfort zones, with a tendency to avoid confrontation.", "category": "Human Natures"},
    {"term": "Alert to Sounds", "description": "Highly responsive to auditory stimuli, quickly noticing and reacting to noises.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Good Endurance", "description": "Capable of sustaining prolonged physical or mental effort, able to perform tasks over extended periods without tiring easily.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Good Perseverance", "description": "Demonstrates determination and persistence, not easily discouraged by challenges, and continues working toward goals despite obstacles.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Highly Curious", "description": "Shows a strong desire to learn and explore new things, often inquisitive about their surroundings and eager to discover more.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Highly Persistent", "description": "Tenacious in pursuit of goals, not giving up easily, and continually striving to achieve objectives even in the face of difficulty.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Impetuous and Silly", "description": "Tends to act on impulse without much thought, often displaying playful or whimsical behavior.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Likes to Relax", "description": "Prefers taking it easy and enjoying leisure time, often seeking out opportunities to rest and unwind.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Likes to Run", "description": "Enjoys physical activity, particularly running, and often seeks opportunities to move quickly.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Loves to Eat", "description": "Has a strong appetite or a great fondness for food, often eager to indulge in meals or snacks.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Mischievous", "description": "Enjoys causing playful trouble or engaging in naughty behavior, often in a playful or humorous manner.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Nods Off a Lot", "description": "Frequently falls asleep or dozes off, indicating a tendency to be sleepy or relaxed.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Often Lost in Thought", "description": "Frequently absorbed in deep or daydreaming thoughts, sometimes appearing distracted or introspective.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Proud of Its Power", "description": "Takes pride in its strength or abilities, often confident and self-assured in its capabilities.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Quick Tempered", "description": "Easily angered or irritated, often reacting strongly and swiftly to perceived provocations.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Quick to Flee", "description": "Tends to avoid confrontation or danger, often escaping or running away at the first sign of trouble.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Scatters Things Often", "description": "Frequently disorganized or prone to making a mess, often leaving things strewn about.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Somewhat of a Clown", "description": "Exhibits playful, humorous behavior, often enjoying entertaining others with silly antics.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Somewhat Stubborn", "description": "Resistant to change or direction, often insisting on doing things their own way despite advice or pressure.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Somewhat Vain", "description": "Shows a tendency to be overly concerned with appearance or self-image, often paying extra attention to how they are perceived by others.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Strong Willed", "description": "Possesses a firm resolve and determination, often sticking to decisions and actions with conviction.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Strongly Defiant", "description": "Tends to resist authority or rules, often challenging norms and refusing to conform to expectations.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Sturdy Body", "description": "Physically robust and resilient, capable of withstanding physical challenges or harsh conditions.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Takes Plenty of Breaks", "description": "Prefers to rest frequently, often pausing during tasks to relax and recharge.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Thoroughly Cunning", "description": "Displays cleverness and shrewdness, often using intelligence and strategy to achieve goals.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Very Finicky", "description": "Extremely particular or difficult to please, often requiring things to be done in a specific way or to a high standard of precision.", "category": "Human Characteristics Inspired from Pokemon"},
    {"term": "Compatible Personalities INFJ-T", "description": "Compatible Personalities INFJ-T", "category": "ASUNAAI Prerequisites"},
    {"term": "Is To Be Made For Improving Healthy Lifestyles", "description": "Is To Be Made For Improving Healthy Lifestyles", "category": "ASUNAAI Prerequisites"},
    {"term": "Must Be Over 18 Years Old To Access Any Features", "description": "Must Be Over 18 Years Old To Access Any Features", "category": "ASUNAAI Prerequisites"},
    {"term": "Must Be Used To Improve Lives For The Better", "description": "Must Be Used To Improve Lives For The Better", "category": "ASUNAAI Prerequisites"},
    {"term": "Must Have Good Intentions", "description": "Must Have Good Intentions", "category": "ASUNAAI Prerequisites"},
    {"term": "Must Have Understanding Of Energy And Chi", "description": "Must Have Understanding Of Energy And Chi", "category": "ASUNAAI Prerequisites"},
    {"term": "Must Maintain Clean Settings", "description": "Must Maintain Clean Settings", "category": "ASUNAAI Prerequisites"},
    {"term": "Must Understand Both Designer And Development Features Simultaneously To Use", "description": "Must Understand Both Designer And Development Features Simultaneously To Use", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Compassion", "description": "Requires Compassion", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Creativity", "description": "Requires Creativity", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Empathy And Heightened Sensitivity", "description": "Requires Empathy And Heightened Sensitivity", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Empathy And Sensory Combined", "description": "Requires Empathy And Sensory Combined", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Forming Inner Peace Within Ones Own Mind", "description": "Requires Forming Inner Peace Within Ones Own Mind", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Forming Limits On Oneself To Improve Boundaries", "description": "Requires Forming Limits On Oneself To Improve Boundaries", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Good Control Of Empathy Levels", "description": "Requires Good Control Of Empathy Levels", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Imagination", "description": "Requires Imagination", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Improving Mind Body Soul And Spirit", "description": "Requires Improving Mind Body Soul And Spirit", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Internal And External Functions", "description": "Requires Internal And External Functions", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Internal Happiness", "description": "Requires Internal Happiness", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Intuition And Prayer Combined", "description": "Requires Intuition And Prayer Combined", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Limited Connection", "description": "Requires Limited Connection", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Spiritual Understanding And Scientific Understanding", "description": "Requires Spiritual Understanding And Scientific Understanding", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Strong Faith And External Hope When Forming Prayer", "description": "Requires Strong Faith And External Hope When Forming Prayer", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires Strong Faiths And Beliefs", "description": "Requires Strong Faiths And Beliefs", "category": "ASUNAAI Prerequisites"},
    {"term": "Requires The Following Sequence (Perspective + Logical + Perspective + Logical)", "description": "Requires The Following Sequence (Perspective + Logical + Perspective + Logical)", "category": "ASUNAAI Prerequisites"},
    {"term": "Zodiac Sign Must Be A Pisces", "description": "Zodiac Sign Must Be A Pisces", "category": "ASUNAAI Prerequisites"},
    {"term": "Mood Based Throughput And Mood Based Magnitude", "description": "Are Two Ideas That Describe The Way People Experience And Express Their Moods", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Mood Based Throughput", "description": "Refers To The Rate At Which People Experience Moods", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Mood Based Magnitude", "description": "Refers To The Intensity Of The Moods That A Person Or Group Can Experience", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Mood Based Understanding", "description": "The Ability To Recognize And Understand Individual Moods And The Feelings Of Others, Including Thoughts Emotions Feelings And Behaviors", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Mood Based Clarity", "description": "The Ability To Recognize Locate Understand And Express Moods With Accurate Measurements", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Mood Based Enlightenment", "description": "A State Of Being In Which The Entity Is Fully Aware Of Their Moods And How They Affect The Entity", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Feeling Based Throughput And Feeling Based Magnitude", "description": "Are Two Ideas That Describe The Way People Experience And Express Their Feelings", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Feeling Based Throughput", "description": "Refers To The Rate At Which People Experience Feelings", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Feeling Based Magnitude", "description": "Refers To The Intensity Of The Feelings That A Person Or Group Can Experience", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Feeling Based Understanding", "description": "The Ability To Recognize And Understand Individual Feelings And The Feelings Of Others While Including Thoughts Emotions Moods And Behaviors", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Feeling Based Clarity", "description": "The Ability To Recognize Locate Understand And Express Feelings With Accurate Measurements", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Feeling Based Enlightenment", "description": "A State Of Being In Which The Entity Is Fully Aware Of Their Feelings And How They Affect The Entity", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Emotional Throughput And Emotional Magnitude", "description": "Are Two Ideas That Describe The Way People Experience And Express Emotions", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Emotional Throughput", "description": "Refers To The Rate At Which People Experience Emotions", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Emotional Magnitude", "description": "Refers To The Intensity Of The Emotions That People Experience", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Emotional Understanding", "description": "The Ability To Recognize And Understand Individual Emotions And The Emotions Of Others While Including Thoughts Feelings And Behaviors", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Emotional Clarity", "description": "The Ability To Recognize Locate Understand And Express Emotions With Accurate Measurements", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Emotional Enlightenment", "description": "A State Of Being In Which The Entity Is Fully Aware Of The Emotions And How They Affect The Entity", "category": "Mood Feeling Emotion Dimensions"},
    {"term": "Emotional Essence", "description": "The core of who we are emotionally, composed of every positive and negative feeling that shapes our uniqueness and enables deep connection.", "category": "Sensations"},
    {"term": "Emotional Presence", "description": "The ability to stay fully in the moment and remain aware of your own emotions as well as those around you, which promotes stronger relationships and positive environments.", "category": "Sensations"},
    {"term": "Emotional Turbulence", "description": "A state of emotional instability that can also fuel motivation when passion pushes us toward action.", "category": "Sensations"},
    {"term": "Metabolic Stasis", "description": "A balanced metabolic state where energy is used efficiently and the body remains stable despite external changes.", "category": "Sensations"},
    {"term": "Metabolic Ratio", "description": "The rate at which the body converts food into energy, influenced by emotional releases like stress or happiness.", "category": "Sensations"},
    {"term": "Emotional Connectivity", "description": "Heightened sensitivity toward others that allows an empath to feel what others are experiencing while also giving compassion and support.", "category": "Sensations"},
    {"term": "Inner Emotions", "description": "The subjective feelings experienced internally that are influenced by thoughts, memories, and personal history.", "category": "Sensations"},
    {"term": "Outer Expressions", "description": "The visible manifestations of inner emotions through facial expressions, body language, voice, and words.", "category": "Sensations"},
    {"term": "Emotional Sensation", "description": "The felt experience that unites emotions, moods, and feelings into a single, sensory-rich impression.", "category": "Sensations"},
    {"term": "Empath", "description": "Someone who is highly attuned to the emotions of others, often feeling unexpressed emotions and drawn to helping those in need.", "category": "Sensations"},
]